import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#fbf9f4",
        "secondary-container": "#c6e9e9",
        "tertiary-container": "#fbd185",
        "on-secondary-fixed-variant": "#416161",
        "surface": "#fbf9f4",
        "error": "#9f403d",
        "tertiary-fixed": "#fbd185",
        "inverse-primary": "#ffffff",
        "inverse-surface": "#0e0e0c",
        "inverse-on-surface": "#9e9d99",
        "on-primary-fixed": "#403f3f",
        "on-surface-variant": "#5e6058",
        "on-secondary-container": "#375757",
        "primary-dim": "#535252",
        "on-surface": "#31332c",
        "on-secondary": "#e0fffe",
        "secondary-dim": "#395959",
        "surface-dim": "#d9dbcf",
        "surface-tint": "#5f5e5e",
        "primary-container": "#e5e2e1",
        "on-primary-container": "#525151",
        "primary-fixed": "#e5e2e1",
        "outline": "#797c73",
        "secondary": "#456565",
        "surface-container-low": "#f5f4ed",
        "on-tertiary-fixed": "#4a3400",
        "on-secondary-fixed": "#244545",
        "on-background": "#31332c",
        "primary": "#5f5e5e",
        "surface-variant": "#e2e3d9",
        "secondary-fixed-dim": "#b8dbda",
        "surface-container-lowest": "#ffffff",
        "error-dim": "#4e0309",
        "surface-container": "#efeee6",
        "background": "#fbf9f4",
        "outline-variant": "#b1b3a9",
        "primary-fixed-dim": "#d6d4d3",
        "error-container": "#fe8983",
        "surface-container-high": "#e8e9e0",
        "on-tertiary-fixed-variant": "#6c500f",
        "tertiary": "#785a1a",
        "on-error-container": "#752121",
        "tertiary-dim": "#6b4e0e",
        "on-primary": "#faf7f6",
        "on-primary-fixed-variant": "#5c5b5b",
        "on-error": "#fff7f6",
        // Keep our radix vars mapping as fallback
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--on-surface))",
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--surface))",
          foreground: "hsl(var(--on-surface))",
        },
      },
      fontFamily: {
        headline: ["Newsreader", "serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        sans: ["Inter", "system-ui", "sans-serif"],
        serif: ["Newsreader", "Georgia", "serif"],
      },
      borderRadius: {
        lg: "0px",
        md: "0px",
        sm: "0px",
      },
    },
  },
  plugins: [],
};
export default config;
